FROM alpine:3
LABEL maintainer="Tonio"

ENV FRP_VERSION 0.33.0

WORKDIR /

RUN wget --no-check-certificate https://github.com/fatedier/frp/releases/download/v${FRP_VERSION}/frp_${FRP_VERSION}_linux_amd64.tar.gz \
    && tar xzf frp_${FRP_VERSION}_linux_amd64.tar.gz \
    && cd frp_${FRP_VERSION}_linux_amd64 \
    && mv frps /frps \
    && mv frps.ini /frps.ini \
    && cd .. \
    && rm -rf *.tar.gz \
    && rm -rf frp_${FRP_VERSION}_linux_amd64

EXPOSE 7000
ENTRYPOINT /frps -c /frps.ini